events { worker_processes 1; }
http {
  upstream game_servers {
    server go-1:8080;
    server go-2:8080;
    server go-3:8080;
  }
  server {
    listen 80;
    location /api/ {
      proxy_pass http://game_servers/;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_cache off;
    }
    location / {
      root /usr/share/nginx/html;
      try_files $uri /index.html;
    }
  }
}
